# Generated by Django 5.2 on 2025-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255, unique=True)),
                ('form_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('form_age', models.PositiveIntegerField()),
                ('form_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('form_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('form_address', models.TextField(blank=True, null=True)),
                ('form_city', models.CharField(blank=True, max_length=100, null=True)),
                ('form_state', models.CharField(blank=True, max_length=100, null=True)),
                ('form_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('form_country', models.CharField(blank=True, max_length=100, null=True)),
                ('form_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('form_skills', models.TextField(blank=True, null=True)),
                ('form_education', models.CharField(blank=True, max_length=255, null=True)),
                ('form_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Detail',
                'verbose_name_plural': 'Form Details',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form_name'], name='Details_for_form_na_f1954d_idx'), models.Index(fields=['form_email'], name='Details_for_form_em_600bef_idx')],
            },
        ),
    ]
